version: '2'

services:
  aso-web:
    container_name: aso-web
    image: registry.gitlab.com/convenia-docker-images/saas/nginx:1.0
    links:
      - aso-app
    volumes:
      - .:/var/www/app
      - ./docker/config/nginx/aso.conf:/etc/nginx/conf.d/asanable.conf
    ports:
      - 8092:8080

  aso-app:
    container_name: aso-app
    image: registry.gitlab.com/convenia-docker-images/base/php7/7.2/fpm:1.3
    links:
      - aso-mysql
    volumes:
      - .:/var/www/app
      - ./docker/config/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  aso-mysql:
    container_name: aso-mysql
    image: registry.gitlab.com/convenia-docker-images/saas/mysql/5.6:1.0
    volumes:
      - aso-mysql-data:/var/lib/mysql
      - ./docker/config/mysql:/etc/mysql/conf.d
    ports:
      - 3308:3306

volumes:
  aso-mysql-data:
    driver: local
